name: Java-CI
on: push

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  Clone-Down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-Down
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/build-app.sh && ci/build-app.sh
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: .
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-Down
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build, Test]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: .
      - run: chmod +x ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/build-docker.sh
      - run: chmod +x ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker.sh
  ComponentTest:
    runs-on: self-hosted
    needs: Docker-image
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - run: chmod +x ci/component-test.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/component-test.sh
    