name: Java-CI
on: push
jobs:
  Clone-Down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-Down
    steps:
      - run: ci/build-app.sh
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-Down
    steps:
      - run: ci/unit-test-app.sh