name: Java-CI
on: push
jobs:
  Clone-Down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-Down
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/build-app.sh && ci/build-app.sh
      - uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-Down
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  Docker-image:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [Build, Test]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dstoft/EficodeGithubActionsKatas:latest
    